# Generated by Django 5.0.2 on 2024-02-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_todo_list_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
