# Generated by Django 5.0.2 on 2024-02-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_todo_category_delete_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
