# Generated by Django 5.0.1 on 2024-02-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
