# Generated by Django 5.0.1 on 2024-02-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.CharField(default='', max_length=10000)),
                ('author', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
